"""
SmartResolve AI — Complaint Routing Model Training Script
Expanded dataset: 150+ samples per category, diverse language, Indian context.
Usage: python train_model.py
"""
import json, os, random
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, accuracy_score
import joblib

TRAINING_DATA = {
"Billing": [
"My credit card was charged twice for the same order",
"I was billed for a service I never subscribed to",
"Incorrect amount deducted from my bank account",
"I need a refund for the duplicate payment made yesterday",
"My invoice shows wrong charges that I did not authorize",
"EMI deducted but loan account still shows amount as due",
"Payment failed but money was deducted from my account",
"I was charged for a cancelled subscription",
"My account was debited without any transaction confirmation",
"Overcharged on my monthly bill by Rs 500",
"Refund not received after 15 days of cancellation",
"Wrong GST amount applied on my invoice",
"Auto-renewal charged without prior notification",
"Double payment deducted for single transaction",
"Bank statement shows unauthorized debit of Rs 2000",
"I want to dispute a charge on my credit card statement",
"Cashback not credited to my account after eligible purchase",
"My wallet balance was deducted but transaction failed",
"Charged premium price for basic plan",
"Late payment fee charged even though I paid on time",
"My payment was deducted but order was not placed",
"Subscription fee charged after I cancelled the plan",
"I received a bill for services not rendered",
"Transaction amount does not match the agreed price",
"Money debited twice from my savings account",
"I need invoice correction for wrong billing address",
"Penalty charged without any prior warning",
"My reward points were not applied to the bill",
"Charged for premium features I never used",
"Billing cycle changed without my consent",
"I was charged international transaction fee on domestic purchase",
"My prepaid balance was deducted without any usage",
"Wrong tax calculation on my monthly statement",
"I need a detailed breakdown of charges on my bill",
"Unexpected charges appeared on my account this month",
"My discount coupon was not applied during checkout",
"I was billed for a product I returned last week",
"Security deposit not refunded after account closure",
"My account shows negative balance due to incorrect deduction",
"I need to update my billing information urgently",
"Amount deducted from UPI but merchant did not receive payment",
"My credit card bill shows a transaction I never made",
"I was charged Rs 999 for a free trial I cancelled",
"My EMI amount changed without any notice from the bank",
"I paid my bill twice by mistake and need a refund",
"The invoice I received has wrong product prices",
"My bank account was debited for a failed transaction",
"I am being charged for a service that was discontinued",
"My annual subscription was renewed without my permission",
"I need a tax invoice for my recent purchase",
"The cashback offer was not applied to my order",
"I was charged delivery fee even though order qualified for free delivery",
"My credit limit was reduced without any notification",
"I received a demand notice for an amount I already paid",
"My payment receipt shows wrong amount",
"I was charged twice for the same hotel booking",
"My insurance premium was deducted twice this month",
"The discount I was promised was not applied to my bill",
"I need a refund for a service that was not delivered as promised",
"My account was charged for a subscription I never signed up for",
"I received an incorrect tax deduction on my salary",
"My electricity bill shows units I never consumed",
"I was charged a processing fee that was not mentioned",
"My loan statement shows incorrect interest calculation",
"I need clarification on the charges in my monthly statement",
"My prepaid plan was changed to postpaid without my consent",
"I was billed for data usage even though I was on WiFi",
"My credit card reward points expired without notification",
"I need a duplicate bill for my recent transaction",
"The refund amount credited is less than what I paid",
"I was charged for a product that was out of stock",
"My account shows a pending charge that I did not authorize",
"I need to dispute an incorrect charge on my account",
"My payment was processed twice due to a technical error",
"I was charged for express delivery but received standard delivery",
"My subscription was not cancelled despite my request",
"I need a refund for an event ticket that was cancelled",
"The price I was charged is different from the price shown",
],
"Technical": [
"The app keeps crashing every time I try to open it",
"I cannot login to my account despite correct credentials",
"Website is showing 404 error on all pages",
"My password reset email is not being received",
"The mobile app is extremely slow and unresponsive",
"Video streaming keeps buffering and stops frequently",
"I am unable to upload documents on the portal",
"Two-factor authentication code is not working",
"The search feature on the website is broken",
"My account got locked after multiple login attempts",
"API integration is returning 500 internal server error",
"Push notifications are not being received on my phone",
"The download button does not work on any browser",
"My profile picture cannot be updated due to upload error",
"The payment gateway times out during checkout",
"I cannot access my dashboard after the recent update",
"The mobile app crashes on Android 13 devices",
"Email verification link is expired immediately",
"The website is not loading on Chrome browser",
"My data is not syncing across devices",
"The OTP is not being delivered to my registered number",
"I am getting SSL certificate error on the website",
"The filter options on the product page are not working",
"My account settings are not being saved",
"The live chat feature is not connecting to any agent",
"I cannot export my data from the platform",
"The map integration is showing wrong location",
"My subscription status shows expired despite recent renewal",
"The barcode scanner in the app is not functioning",
"I am unable to delete my account from the settings",
"The report generation feature is throwing an error",
"My calendar integration stopped working after update",
"The dark mode toggle is not working properly",
"I cannot change my registered email address",
"The app is consuming too much battery and data",
"My saved preferences are being reset every session",
"The voice search feature is not recognizing my commands",
"I am getting duplicate notifications for same event",
"The QR code scanner is not reading codes correctly",
"My account dashboard is showing incorrect statistics",
"The website keeps logging me out automatically",
"I cannot access the admin panel after password change",
"The mobile app is not available on my device model",
"My internet connection is fine but the app shows offline",
"The video call feature is not working on the platform",
"I cannot print documents from the web application",
"The autocomplete feature is suggesting wrong results",
"My account was automatically logged out during a transaction",
"The app update broke several features that were working before",
"I am unable to share files through the platform",
"The notification settings are not being saved",
"My account shows wrong timezone despite correct settings",
"The platform is not compatible with my operating system",
"I cannot access my account history beyond 3 months",
"The bulk upload feature is failing for large files",
"My two-factor authentication app is not syncing",
"The website form is not submitting despite correct data",
"I am getting a white screen after logging in",
"The platform is extremely slow during peak hours",
"My account was compromised due to a security vulnerability",
"The email integration is not working with my email client",
"I cannot generate reports in PDF format",
"The mobile app does not support my screen resolution",
"My data was lost after the recent platform migration",
"The API documentation is outdated and incorrect",
"I am unable to integrate the platform with third-party tools",
"The platform crashes when I try to process large datasets",
"My account permissions are not working as configured",
"The search results are not relevant to my query",
"I cannot access the platform from my office network",
"The platform does not work on Safari browser",
"My account shows wrong language despite correct settings",
"The platform is not sending automated emails",
"I cannot recover my account as the recovery email is wrong",
"The platform is showing cached data instead of live data",
"My account was merged with another account by mistake",
"The platform does not support my preferred payment method",
"I am getting CORS errors when using the API",
"The platform is not accessible on mobile devices",
"My account data is not being backed up properly",
],
"Delivery": [
"My order has not been delivered after 10 days",
"The package was delivered to the wrong address",
"I received a damaged product in the delivery",
"My order shows delivered but I never received it",
"The delivery was attempted when I was home but no one knocked",
"I need to change my delivery address urgently",
"My order has been stuck in transit for 5 days",
"The delivery partner is not responding to calls",
"I received an empty box instead of the product",
"My order was cancelled without any notification",
"The estimated delivery date keeps getting pushed",
"I received someone else order by mistake",
"My package was returned to sender without delivery attempt",
"The tracking number is not showing any updates",
"I need express delivery but standard was applied",
"My order was partially delivered with items missing",
"The delivery agent demanded extra charges at doorstep",
"My fragile item was not packed properly and broke",
"I have been waiting for my order for 3 weeks now",
"The delivery was made to a neighbor without my consent",
"My order tracking shows out for delivery for 2 days",
"I need to reschedule my delivery to a different date",
"The courier company lost my package in transit",
"My order was delivered to the wrong city",
"I received a counterfeit product instead of original",
"The delivery slot I selected was not honored",
"My order was marked delivered but tracking shows in warehouse",
"I need to return the product but pickup is not scheduled",
"The delivery partner left the package outside without informing",
"My international shipment is stuck at customs",
"I ordered 3 items but only 2 were delivered",
"The product seal was broken when I received it",
"My same-day delivery order arrived 3 days late",
"The delivery address was correct but package went elsewhere",
"I need urgent delivery for a medical device",
"My order was delivered to a different floor in my building",
"The package was wet and damaged due to improper handling",
"I have not received any tracking information for my order",
"My subscription box was not delivered this month",
"The delivery was made to an old address despite update",
"My order is showing as delivered but I was not home",
"The courier attempted delivery at wrong time despite instructions",
"My package has been at the local facility for 4 days",
"I need to track my shipment but the tracking link is broken",
"The delivery partner is not picking up the return request",
"My order was split into multiple shipments without notice",
"The delivery estimate was 2 days but it has been 7 days",
"I received a notification that my order was delivered but nothing arrived",
"My package was delivered to the security guard without my knowledge",
"The delivery partner marked the package as undeliverable incorrectly",
"I need to change the delivery time slot for my order",
"My order was returned to origin without any delivery attempt",
"The package I received has someone else name on it",
"I need urgent delivery rescheduling due to travel",
"My order tracking has not updated in 3 days",
"The delivery partner is asking for additional charges",
"My order was delivered in damaged packaging",
"I received a partial shipment and the rest is missing",
"The delivery was made to a wrong building in my area",
"My order shows out for delivery since morning but not arrived",
"I need to file a complaint about a rude delivery agent",
"My package was left in the rain and the contents are damaged",
"The delivery partner did not follow the delivery instructions",
"My order was cancelled by the seller after payment",
"I need to intercept my package as I will not be home",
"The delivery partner is not available on the contact number",
"My order has been in processing state for 5 days",
"I received a wrong item in my order",
"The delivery was made to a different pin code",
"My order was delivered to an old address I had deleted",
"I need a delivery confirmation for my records",
"The package was delivered without obtaining my signature",
"My order is showing as returned but I never refused delivery",
],
"Product": [
"The product I received does not match the description",
"My new laptop stopped working after 2 days of use",
"The product quality is very poor compared to what was shown",
"I received a used product instead of a new one",
"The product has manufacturing defects",
"My phone battery drains completely within 2 hours",
"The product dimensions are different from what was listed",
"I received the wrong color variant of the product",
"The product stopped working within the warranty period",
"My appliance is making unusual noise during operation",
"The product packaging was misleading about the contents",
"I received an older model instead of the latest version",
"The product has scratches and dents on arrival",
"My electronic device is overheating during normal use",
"The product accessories were missing from the box",
"I received a product with expired warranty",
"The product does not work as advertised",
"My device screen has dead pixels from day one",
"The product material is different from what was described",
"I need a replacement for the defective product",
"The product manual is in a foreign language only",
"My product stopped working after the first use",
"The product has a strong chemical smell",
"I received a product with wrong specifications",
"The product is not compatible with my existing setup",
"My product warranty claim is being rejected unfairly",
"The product has safety issues that need immediate attention",
"I received a product with missing parts",
"The product performance is far below expectations",
"My product developed a fault within 30 days of purchase",
"The product color faded after first wash",
"I need a product recall for the defective batch",
"The product size chart was inaccurate",
"My product is not charging properly",
"The product has a design flaw that causes injury risk",
"I received a product that was clearly previously returned",
"The product does not fit as described in measurements",
"My product remote control stopped working",
"The product has rust and corrosion on arrival",
"I need urgent replacement for a safety-critical product defect",
"The product I bought is not genuine and appears to be fake",
"My television screen developed lines after 1 month of use",
"The refrigerator I purchased is not cooling properly",
"My washing machine is leaking water from the bottom",
"The air conditioner is not cooling despite being serviced",
"My microwave oven stopped working after 3 uses",
"The blender I purchased broke during first use",
"My camera lens has a scratch that was not mentioned",
"The headphones I received have only one side working",
"My smartwatch screen cracked without any impact",
"The product I received is a different brand than ordered",
"My laptop keyboard has keys that are not responding",
"The product I ordered was discontinued but I was not informed",
"My printer is not printing despite correct installation",
"The product I received has a manufacturing date of 2 years ago",
"My electric kettle is not heating water properly",
"The product I purchased has a broken zipper",
"My gaming console is not reading game discs",
"The product I received has a different serial number than the box",
"My fitness tracker is showing incorrect health data",
"The product I ordered is not suitable for Indian voltage",
"My speaker has distorted sound from day one",
"The product I received has a cracked screen",
"My electric toothbrush stopped charging after a week",
"The product I purchased has a strong plastic smell",
"My tablet is not connecting to WiFi despite correct settings",
"The product I received is missing the warranty card",
"My electric iron is not heating evenly",
"The product I ordered came without the promised accessories",
"My power bank is not charging my devices",
"The product I received has a different model number",
],
"Service": [
"The customer support agent was very rude to me",
"I have been waiting for a callback for 3 days",
"My complaint was closed without being resolved",
"The service technician did not show up for the appointment",
"I am being transferred between departments without resolution",
"The service quality has deteriorated significantly",
"My service request has been pending for 2 weeks",
"The agent gave me wrong information about my account",
"I need to speak to a senior manager about my issue",
"My complaint keeps getting reopened without resolution",
"The service center is not accepting my warranty claim",
"I was promised a resolution in 24 hours but nothing happened",
"The support team is not understanding my issue",
"My service appointment was cancelled without notice",
"I am not satisfied with the resolution provided",
"The agent disconnected my call without resolving the issue",
"I have raised the same complaint 5 times with no result",
"The service team is not following up on my case",
"My escalation request is being ignored",
"The customer care number is always busy",
"I need compensation for the poor service experience",
"The service engineer damaged my property during repair",
"My complaint was marked resolved without my confirmation",
"The support chat is not connecting to any agent",
"I am getting contradictory information from different agents",
"My service level agreement is being violated",
"The after-sales service is extremely poor",
"I need a dedicated account manager for my issues",
"The service team lacks knowledge about their own products",
"My feedback about poor service is being ignored",
"The repair service took 3 times longer than promised",
"I was charged for a service visit that was supposed to be free",
"The service team did not fix the root cause of the problem",
"My complaint history is not being maintained properly",
"The service quality is inconsistent across different agents",
"I need urgent service for a critical business issue",
"The support team is not available during promised hours",
"My service contract terms are not being honored",
"The agent promised features that do not exist",
"I need a formal apology for the poor service received",
"The customer service representative was dismissive of my issue",
"I have been on hold for 2 hours without any response",
"The service team closed my ticket without contacting me",
"I need to escalate my complaint to the grievance officer",
"The service quality I received does not match what was promised",
"My service request was assigned to the wrong department",
"The technician who visited was not qualified to fix my issue",
"I am not getting any updates on my service request",
"The service center refused to honor my warranty",
"I need a written acknowledgment of my complaint",
"The customer support is only available in English but I need Hindi support",
"My complaint was not registered despite calling multiple times",
"The service team is blaming me for a manufacturing defect",
"I need a home visit service but only center visits are offered",
"The service representative gave me incorrect troubleshooting steps",
"My service request has been pending beyond the promised timeline",
"The service team is not responding to my emails",
"I need urgent assistance but the priority queue is not working",
"The service center is too far from my location",
"I was treated poorly at the service center",
"The service team is not acknowledging my previous complaint",
"My service request was cancelled without my knowledge",
"The service team is asking for documents I already submitted",
"I need a service report for my insurance claim",
"The service team is not available on weekends",
"My complaint was transferred to a third party without my consent",
"The service team is not providing updates despite my follow-ups",
"I need a replacement service technician as the current one is incompetent",
"The service team is not honoring the extended warranty I purchased",
"My service request is being delayed due to spare parts unavailability",
"The service team is charging for repairs covered under warranty",
"I need a supervisor to review my case immediately",
],
"Account": [
"I cannot access my account after password reset",
"My account has been suspended without any reason",
"I need to update my registered mobile number",
"My account was hacked and I need immediate help",
"I want to close my account and get my data deleted",
"My account details are showing incorrect information",
"I cannot verify my identity for account recovery",
"My account was merged with another account by mistake",
"I need to transfer my account to a different email",
"My account privileges were downgraded without notice",
"I am unable to add a new payment method to my account",
"My account history is missing important transactions",
"I need to update my KYC documents on the account",
"My account is showing wrong subscription plan",
"I cannot remove an old device from my account",
"My account was created without my consent",
"I need to change my account username",
"My linked bank account details are incorrect",
"I cannot see my previous orders in account history",
"My account security settings were changed without my knowledge",
"I need to add a family member to my account",
"My account verification is stuck in pending state",
"I cannot update my address in the account settings",
"My account is showing activity from unknown locations",
"I need to recover my account after losing access to email",
"My account tier was downgraded despite meeting criteria",
"I cannot link my social media account for login",
"My account preferences are not being saved",
"I need to separate my personal and business accounts",
"My account was flagged for suspicious activity incorrectly",
"I cannot see my loyalty points in my account",
"My account profile photo cannot be updated",
"I need to enable two-factor authentication on my account",
"My account is showing wrong membership expiry date",
"I cannot access my account from a new device",
"My account was deactivated during an active subscription",
"I need to update my nominee details on the account",
"My account is not reflecting recent changes",
"I cannot download my account statement",
"My account permissions need to be updated urgently",
"I need to merge two accounts that belong to me",
"My account was blocked due to suspicious login attempts",
"I need to update my PAN card details on my account",
"My account is showing wrong date of birth",
"I cannot change my account password as I forgot the old one",
"My account is linked to a wrong Aadhaar number",
"I need to deactivate my account temporarily",
"My account is showing wrong gender information",
"I cannot access my account as my phone number changed",
"My account was created with wrong email address",
"I need to update my bank account details for refunds",
"My account is showing wrong address for deliveries",
"I cannot see my saved addresses in my account",
"My account is not showing my premium membership benefits",
"I need to change the primary account holder name",
"My account is linked to an old phone number I no longer use",
"I cannot access my account as I changed my email",
"My account is showing wrong order history",
"I need to update my GST number on my business account",
"My account is not showing my referral rewards",
"I cannot access my account as the OTP is going to old number",
"My account was suspended due to a policy violation I did not commit",
"I need to reactivate my dormant account",
"My account is showing wrong credit score",
"I cannot update my account as the verification is failing",
"My account is linked to wrong UPI ID",
"I need to change my account type from individual to business",
"My account is not showing my cashback balance",
"I cannot see my saved payment methods in my account",
"My account is showing wrong subscription renewal date",
"I need to update my emergency contact details on my account",
],
"Refund": [
"I have not received my refund after 30 days",
"My refund was processed for wrong amount",
"I need a refund for a service that was not delivered",
"My refund request was rejected without valid reason",
"The refund was credited to wrong account",
"I need urgent refund for a fraudulent transaction",
"My refund status has been pending for 3 weeks",
"I was promised a refund but it never came",
"My partial refund is missing the remaining amount",
"I need a refund for a product that was out of stock",
"My refund was reversed after being credited",
"I need a refund for duplicate charges on my account",
"The refund timeline given was not honored",
"My refund request keeps getting rejected automatically",
"I need a refund for a cancelled flight booking",
"My insurance claim refund has not been processed",
"I need a refund for an event that was cancelled",
"My refund was processed but not received in bank",
"I need a refund for a subscription I never used",
"My refund amount does not include the taxes paid",
"I need a refund for a hotel booking that was cancelled",
"My refund was split into multiple transactions incorrectly",
"I need a refund for a course I could not attend",
"My refund request was closed without processing",
"I need a refund for a defective product I returned",
"My refund is being delayed due to bank processing issues",
"I need a refund for an unauthorized transaction",
"My refund was credited to an expired card",
"I need a refund for a service downgrade",
"My refund request needs escalation to finance team",
"I need a refund for a promotional offer that was not honored",
"My refund was processed in wrong currency",
"I need a refund for a membership I want to cancel",
"My refund confirmation email was never received",
"I need a refund for a product damaged during delivery",
"My refund is stuck in processing state for 2 weeks",
"I need a refund for a service that was overcharged",
"My refund was applied as store credit without my consent",
"I need a refund for a booking made by mistake",
"My refund dispute has not been resolved",
"I returned the product 10 days ago but refund is not initiated",
"My refund of Rs 5000 has not been credited despite approval",
"I need a refund for a train ticket I cancelled",
"My refund was processed to a closed bank account",
"I need a refund for a prepaid service that was not activated",
"My refund request was denied citing wrong policy",
"I need a refund for a duplicate order that was placed",
"My refund has been approved but not credited for 15 days",
"I need a refund for a product that was recalled",
"My refund amount is less than the original payment",
"I need a refund for a service that was cancelled by the company",
"My refund was processed but the bank says they did not receive it",
"I need a refund for an incorrect charge on my credit card",
"My refund request is pending for more than the promised 7 days",
"I need a refund for a gift card that was not delivered",
"My refund was credited to wrong UPI ID",
"I need a refund for a subscription that auto-renewed",
"My refund request was rejected citing terms and conditions",
"I need a refund for a product that was not as described",
"My refund is showing as processed but not in my account",
"I need a refund for a service that was discontinued",
"My refund was processed but deducted as a fee",
"I need a refund for a cancelled appointment",
"My refund request has been escalated but no update",
"I need a refund for a wrong item that was delivered",
"My refund was credited to a different account number",
"I need a refund for a product that was never shipped",
"My refund request is being ignored despite multiple follow-ups",
"I need a refund for a service that did not meet expectations",
"My refund was processed in installments without my consent",
"I need a refund for a booking that was cancelled due to weather",
"My refund has been pending since last month",
],
}

def augment_text(text: str) -> list:
    variations = [text]
    prefixes = ["Urgent: ","URGENT - ","Critical issue: ","Please help - ","I am very frustrated - ",
                "This is unacceptable - ","Third time complaining - ","Extremely disappointed - ",
                "Need immediate help - ","This is ridiculous - "]
    suffixes = [" Please resolve immediately."," This has been going on for days.",
                " I need this fixed today."," Very disappointed with the service.",
                " Please escalate this issue."," I will take legal action if not resolved.",
                " This is affecting my business."," I am a premium customer.",
                " Please treat this as high priority."," I have been a loyal customer for 5 years."]
    if random.random() > 0.5:
        variations.append(random.choice(prefixes) + text)
    if random.random() > 0.5:
        variations.append(text + random.choice(suffixes))
    if random.random() > 0.7:
        variations.append(random.choice(prefixes) + text + random.choice(suffixes))
    return variations


def build_dataset():
    texts, labels = [], []
    for category, complaints in TRAINING_DATA.items():
        for complaint in complaints:
            for text in augment_text(complaint):
                texts.append(text)
                labels.append(category)
    return texts, labels


def train():
    print("=" * 60)
    print("SmartResolve AI — Complaint Routing Model Training")
    print("=" * 60)

    texts, labels = build_dataset()
    print(f"\n✓ Dataset: {len(texts)} samples across {len(set(labels))} categories")
    for cat in sorted(set(labels)):
        print(f"  {cat}: {labels.count(cat)}")

    X_train, X_test, y_train, y_test = train_test_split(
        texts, labels, test_size=0.15, random_state=42, stratify=labels
    )
    print(f"\n✓ Train: {len(X_train)} | Test: {len(X_test)}")

    pipeline = Pipeline([
        ('tfidf', TfidfVectorizer(
            ngram_range=(1, 3),
            max_features=25000,
            min_df=1,
            sublinear_tf=True,
            strip_accents='unicode',
            analyzer='word',
            token_pattern=r'\w{2,}',
        )),
        ('clf', LogisticRegression(
            C=10.0,
            max_iter=2000,
            solver='lbfgs',
            multi_class='multinomial',
            random_state=42,
            class_weight='balanced',
        ))
    ])

    print("\n⏳ Training...")
    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    cv_scores = cross_val_score(pipeline, texts, labels, cv=5, scoring='accuracy')

    print(f"\n✓ Test Accuracy:        {accuracy * 100:.1f}%")
    print(f"✓ Cross-validation:     {cv_scores.mean() * 100:.1f}% ± {cv_scores.std() * 100:.1f}%")

    report = classification_report(y_test, y_pred, output_dict=True)
    print("\n📊 Per-category:")
    for cat in sorted(TRAINING_DATA.keys()):
        if cat in report:
            r = report[cat]
            print(f"  {cat:12} P:{r['precision']:.2f} R:{r['recall']:.2f} F1:{r['f1-score']:.2f}")

    os.makedirs("models", exist_ok=True)
    joblib.dump(pipeline, "models/complaint_classifier.pkl")
    print(f"\n✓ Model saved → models/complaint_classifier.pkl")

    training_report = {
        "accuracy": round(accuracy * 100, 1),
        "cv_mean": round(cv_scores.mean() * 100, 1),
        "cv_std": round(cv_scores.std() * 100, 1),
        "total_samples": len(texts),
        "categories": list(TRAINING_DATA.keys()),
        "per_category": {
            cat: {
                "precision": round(report[cat]["precision"] * 100, 1),
                "recall": round(report[cat]["recall"] * 100, 1),
                "f1": round(report[cat]["f1-score"] * 100, 1),
            }
            for cat in TRAINING_DATA.keys() if cat in report
        },
        "model_type": "TF-IDF + Logistic Regression",
        "features": 25000,
        "ngram_range": "1-3",
    }
    with open("models/training_report.json", "w") as f:
        json.dump(training_report, f, indent=2)
    print("✓ Report saved → models/training_report.json")
    print(f"\n{'='*60}")
    print(f"✅ Done! Accuracy: {accuracy * 100:.1f}%")
    print(f"{'='*60}")
    return pipeline, training_report


if __name__ == "__main__":
    train()
